"""LangGraph orchestration for job analysis and application preparation."""

import json
import logging
import operator
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from typing import Annotated, Any, Literal, Protocol, TypedDict

from langgraph.graph import END, START, StateGraph

from models.candidate_context import NormalizedCandidateProfile
from models.job_profile import JobProfile
from services.job_matching import JobMatchingEngine

logger = logging.getLogger(__name__)

SerializableDict = dict[str, Any]


class JobAgentState(TypedDict, total=False):
    """Serializable shared state for the JobPilot application workflow."""

    candidate_profile: SerializableDict
    raw_job_description: str
    job: SerializableDict
    match_result: SerializableDict
    company_research: SerializableDict
    application_content: SerializableDict
    validation_result: SerializableDict
    interview_content: SerializableDict
    messages: Annotated[list[SerializableDict], operator.add]
    execution_log: Annotated[list[str], operator.add]
    minimum_match_score: float
    include_interview: bool
    write_attempts: int


CompanyResearcher = Callable[[SerializableDict], Mapping[str, Any]]
ApplicationWriter = Callable[[JobAgentState], Mapping[str, Any]]
ContentCritic = Callable[[SerializableDict, SerializableDict], Mapping[str, Any]]
InterviewPreparer = Callable[[JobAgentState], Mapping[str, Any]]
ProfileLoader = Callable[[], Mapping[str, Any]]


class JobAnalyzer(Protocol):
    """Boundary for a structured job-description analyzer."""

    def analyze(self, job_description: str) -> JobProfile:
        """Return a validated structured job profile."""
        ...


def _serializable(value: Mapping[str, Any]) -> SerializableDict:
    """Copy provider output through JSON to guarantee serializable graph state."""
    return json.loads(json.dumps(dict(value), default=str))


def _default_company_research(job: SerializableDict) -> SerializableDict:
    """Return a safe placeholder until a public research provider is connected."""
    company = str(job.get("company") or "the company")
    return {
        "company": company,
        "status": "not_researched",
        "summary": f"Public company research has not been requested for {company} yet.",
        "sources": [],
    }


def _default_application_writer(state: JobAgentState) -> SerializableDict:
    """Create a factual outline without inventing candidate achievements."""
    profile = state.get("candidate_profile", {})
    job = state.get("job", {})
    match = state.get("match_result", {})
    name = str(profile.get("name") or "Candidate")
    title = str(job.get("job_title") or "this role")
    strengths = [str(value) for value in match.get("strong_matches", [])[:4]]
    return {
        "format": "outline",
        "headline": f"Application outline for {name} — {title}",
        "strengths_to_highlight": strengths,
        "body": (
            "A full tailored draft can be generated by injecting an LLM-backed "
            "application writer into this workflow."
        ),
        "claims": [],
    }


def _default_critic(
    application: SerializableDict, candidate: SerializableDict
) -> SerializableDict:
    """Conservatively reject explicit claims that are absent from candidate data."""
    candidate_text = json.dumps(candidate, sort_keys=True).casefold()
    claims = [str(value).strip() for value in application.get("claims", []) if str(value).strip()]
    unsupported = [claim for claim in claims if claim.casefold() not in candidate_text]
    return {
        "passed": not unsupported,
        "unsupported_claims": unsupported,
        "feedback": (
            "Remove or rewrite unsupported claims." if unsupported else "All explicit claims are supported."
        ),
    }


def _default_interview_preparer(state: JobAgentState) -> SerializableDict:
    """Create deterministic interview topics from the structured match result."""
    job = state.get("job", {})
    match = state.get("match_result", {})
    return {
        "job_title": str(job.get("job_title") or "Role"),
        "focus_topics": [str(value) for value in match.get("strong_matches", [])[:5]],
        "gap_questions": [str(value) for value in match.get("missing_requirements", [])[:5]],
    }


@dataclass(frozen=True)
class JobWorkflowDependencies:
    """Explicit dependency boundary for deterministic functions and AI services."""

    profile_loader: ProfileLoader
    job_analyzer: JobAnalyzer
    match_engine: JobMatchingEngine
    company_researcher: CompanyResearcher = _default_company_research
    application_writer: ApplicationWriter = _default_application_writer
    critic: ContentCritic = _default_critic
    interview_preparer: InterviewPreparer = _default_interview_preparer
    max_write_attempts: int = 2


class JobApplicationWorkflow:
    """Node implementations and routing rules for the application graph."""

    def __init__(self, dependencies: JobWorkflowDependencies) -> None:
        self._dependencies = dependencies

    @staticmethod
    def _trace(node: str) -> dict[str, list[Any]]:
        logger.info("Job agent node executed: %s", node)
        return {
            "execution_log": [node],
            "messages": [{"role": "system", "content": f"Executed {node}"}],
        }

    def load_profile(self, state: JobAgentState) -> SerializableDict:
        """Load the normalized profile unless serializable data is already supplied."""
        candidate = state.get("candidate_profile") or _serializable(
            self._dependencies.profile_loader()
        )
        NormalizedCandidateProfile.model_validate(candidate)
        return {"candidate_profile": candidate, **self._trace("profile_loader")}

    def analyze_job(self, state: JobAgentState) -> SerializableDict:
        """Convert raw job text into validated, serializable structured data."""
        existing = state.get("job")
        if existing and existing.get("job_title"):
            job = JobProfile.model_validate(existing)
        else:
            description = state.get("raw_job_description", "").strip()
            job = self._dependencies.job_analyzer.analyze(description)
        return {
            "job": job.model_dump(mode="json"),
            **self._trace("job_analyzer"),
        }

    def calculate_match(self, state: JobAgentState) -> SerializableDict:
        """Run the existing deterministic match engine as normal Python code."""
        candidate = NormalizedCandidateProfile.model_validate(state["candidate_profile"])
        job = JobProfile.model_validate(state["job"])
        result = self._dependencies.match_engine.match(candidate, job)
        return {
            "match_result": result.model_dump(mode="json"),
            **self._trace("match_agent"),
        }

    def explain_weak_match(self, state: JobAgentState) -> SerializableDict:
        """Stop expensive downstream work and summarize deterministic match gaps."""
        result = state.get("match_result", {})
        score = float(result.get("overall_match", 0))
        missing = [str(value) for value in result.get("missing_requirements", [])[:3]]
        explanation = f"Match is {score:.0f}%, below the configured threshold."
        if missing:
            explanation += f" Main gaps: {', '.join(missing)}."
        trace = self._trace("weak_match_explainer")
        trace["messages"].append({"role": "assistant", "content": explanation})
        return trace

    def research_company(self, state: JobAgentState) -> SerializableDict:
        """Delegate optional public company research through an injectable boundary."""
        research = _serializable(self._dependencies.company_researcher(state["job"]))
        return {
            "company_research": research,
            **self._trace("company_research_agent"),
        }

    def write_application(self, state: JobAgentState) -> SerializableDict:
        """Generate or revise application content using only current graph state."""
        content = _serializable(self._dependencies.application_writer(state))
        return {
            "application_content": content,
            "write_attempts": state.get("write_attempts", 0) + 1,
            **self._trace("application_writer_agent"),
        }

    def critique(self, state: JobAgentState) -> SerializableDict:
        """Validate generated content for unsupported candidate claims."""
        validation = _serializable(
            self._dependencies.critic(
                state.get("application_content", {}),
                state["candidate_profile"],
            )
        )
        validation.setdefault("passed", False)
        validation.setdefault("unsupported_claims", [])
        return {
            "validation_result": validation,
            **self._trace("critic_agent"),
        }

    def prepare_interview(self, state: JobAgentState) -> SerializableDict:
        """Prepare interview focus areas when the caller requests that branch."""
        content = _serializable(self._dependencies.interview_preparer(state))
        return {
            "interview_content": content,
            **self._trace("interview_agent"),
        }

    @staticmethod
    def route_after_match(
        state: JobAgentState,
    ) -> Literal["explain_weak_match", "company_research"]:
        """Skip expensive work when deterministic match is below the threshold."""
        score = float(state.get("match_result", {}).get("overall_match", 0))
        configured = state.get("minimum_match_score")
        if configured is None:
            configured = float(
                state.get("candidate_profile", {})
                .get("job_preferences", {})
                .get("minimum_match_score", 70)
            )
        return "company_research" if score >= float(configured) else "explain_weak_match"

    def route_after_critic(
        self, state: JobAgentState
    ) -> Literal["rewrite", "interview", "end"]:
        """Bound rewrite loops and optionally continue to interview preparation."""
        passed = bool(state.get("validation_result", {}).get("passed", False))
        attempts = int(state.get("write_attempts", 0))
        if not passed and attempts < max(1, self._dependencies.max_write_attempts):
            return "rewrite"
        if passed and state.get("include_interview", False):
            return "interview"
        return "end"


def build_job_application_graph(dependencies: JobWorkflowDependencies):  # type: ignore[no-untyped-def]
    """Compile the conditional JobPilot application workflow."""
    workflow = JobApplicationWorkflow(dependencies)
    builder = StateGraph(JobAgentState)
    builder.add_node("profile_loader", workflow.load_profile)
    builder.add_node("job_analyzer", workflow.analyze_job)
    builder.add_node("match_agent", workflow.calculate_match)
    builder.add_node("explain_weak_match", workflow.explain_weak_match)
    builder.add_node("company_research", workflow.research_company)
    builder.add_node("application_writer", workflow.write_application)
    builder.add_node("critic", workflow.critique)
    builder.add_node("interview", workflow.prepare_interview)

    builder.add_edge(START, "profile_loader")
    builder.add_edge("profile_loader", "job_analyzer")
    builder.add_edge("job_analyzer", "match_agent")
    builder.add_conditional_edges(
        "match_agent",
        workflow.route_after_match,
        {
            "explain_weak_match": "explain_weak_match",
            "company_research": "company_research",
        },
    )
    builder.add_edge("explain_weak_match", END)
    builder.add_edge("company_research", "application_writer")
    builder.add_edge("application_writer", "critic")
    builder.add_conditional_edges(
        "critic",
        workflow.route_after_critic,
        {
            "rewrite": "application_writer",
            "interview": "interview",
            "end": END,
        },
    )
    builder.add_edge("interview", END)
    return builder.compile()
